[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = false
chain_id = 8453

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
